services:
  pgsql:
    container_name: pgsql_dj_tailwind_react
    image: postgres:16
    ports:
      - '5012:5432'
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: unless-stopped
    networks:
      dj-tailwind-net:
        ipv4_address: 172.1.112.11

networks:
  dj-tailwind-net:
    ipam:
      driver: default
      config:
        - subnet: 172.1.112.0/24